[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dex = "FA8G3TKwgPjjsbF1w7sm7VzUnFWe93faeFeQCCrvjMTt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=3df5f1e8-ed02-460e-98db-c7fa20688dad"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
