[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dex = "BNmapsBA72Egnxd6H25UEuWmbtBKuXLD5stHQqDo6eg6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
